services:
  - type: web
    name: remove-manga-separation
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
